"""empty message

Revision ID: 0f204ee9520b
Revises: 121d7ed93e42
Create Date: 2025-12-27 17:43:56.616881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f204ee9520b'
down_revision = '121d7ed93e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('instalacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.alter_column('instalacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('instalaciones', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
