"""empty message

Revision ID: 121d7ed93e42
Revises: 
Create Date: 2025-12-26 21:10:36.034874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '121d7ed93e42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mantenimiento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='fotos_empresa_id_fkey'),
    sa.ForeignKeyConstraint(['mantenimiento_id'], ['mantenimientos.id'], name='fotos_mantenimiento_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fotos_pkey')
    )
    # ### end Alembic commands ###
