"""empty message

Revision ID: 31df229ff826
Revises: 826f2d12daa5
Create Date: 2026-01-06 19:24:47.895212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31df229ff826'
down_revision = '826f2d12daa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tecnico_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['tecnico_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tecnico_id')

    # ### end Alembic commands ###
