"""empty message

Revision ID: c8e8c066c391
Revises: 31df229ff826
Create Date: 2026-01-06 19:30:40.386264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e8c066c391'
down_revision = '31df229ff826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.drop_index('idx_pendiente_instalacion')
        batch_op.drop_constraint('pendientes_tecnico_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('pendientes_instalacion_id_fkey', type_='foreignkey')
        batch_op.drop_column('tecnico_id')
        batch_op.drop_column('instalacion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instalacion_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tecnico_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('pendientes_instalacion_id_fkey', 'instalaciones', ['instalacion_id'], ['id'])
        batch_op.create_foreign_key('pendientes_tecnico_id_fkey', 'usuarios', ['tecnico_id'], ['id'])
        batch_op.create_index('idx_pendiente_instalacion', ['instalacion_id'], unique=False)

    # ### end Alembic commands ###
