"""empty message

Revision ID: eddc7f3ff02f
Revises: c8e8c066c391
Create Date: 2026-01-06 20:53:26.517056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddc7f3ff02f'
down_revision = 'c8e8c066c391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instalacion_id', sa.Integer(), nullable=False))
        batch_op.create_index('idx_pendiente_instalacion', ['instalacion_id'], unique=False)
        batch_op.create_foreign_key(None, 'instalaciones', ['instalacion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_pendiente_instalacion')
        batch_op.drop_column('instalacion_id')

    # ### end Alembic commands ###
